[package]
name = "poseidon"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hasher.workspace = true
ark-bn254.workspace = true
ark-ff.workspace = true
once_cell.workspace = true
ruint.workspace = true
