[package]
name = "keccak"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hasher = { workspace = true }
tiny-keccak = { workspace = true }

[features]
default = ["sha3"]
sha3 = ["tiny-keccak/sha3"]
